### ISSUE TITLE
README clarification

### ISSUE THREAD

**Issue by AyOhEe** [ChloePrime/Lolidot#2]
### Tested versions

N/A

### System information

N/A

### Issue description

> For improving the core of the engine, e.g. implementation of signals in C#.

Care to elaborate? Signals already exist in C#.

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by ChloePrime** [comment]
Currently custom C# signals are backed by C# events,
Which don't have auto cleanup when the bound object is freed,
and the receiver of that C# Action and captured local variables will be garbage object forever,
which will cause memory leak :(

**Comment by ChloePrime** [comment]
Fixed in #3
